<a href="https://colab.research.google.com/github/yoonputer/test_deeplearning/blob/master/diff_sigmoid_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# sigmoid

In [1]:
import tensorflow as tf

In [5]:
a = tf.constant([4.0,1.0,3.0], dtype = tf.float32)
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [6]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [7]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

# softmax

In [8]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.4901512 ,  1.4013497 , -0.05918949]], dtype=float32)>

In [9]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.24602471, 0.6119377 , 0.14203754]], dtype=float32)>

In [10]:
outputs.numpy()

array([[0.24602471, 0.6119377 , 0.14203754]], dtype=float32)