<a href="https://colab.research.google.com/github/yoonputer/test_deeplearning/blob/master/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
import pandas as pd
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [8]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_iris.to_sql('iris_resource', connect, if_exists='append', index=False)

In [9]:
df_load = pd.read_sql_query('select * from iris_resource',connect)
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [10]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [13]:
import numpy as np

In [14]:
y_data = iris.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

In [12]:
import tensorflow as tf

In [19]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(4,))) # input layer 

model.add(tf.keras.layers.Dense(64, activation='relu')) # hidden layer
model.add(tf.keras.layers.Dense(64, activation='relu')) # hidden layer

model.add(tf.keras.layers.Dense(3, activation='softmax')) # output layer

model.compile(optimizer='adam', loss='mse',metrics=['acc']) #

In [20]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 64)                320       
_________________________________________________________________
dense_4 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 195       
Total params: 4,675
Trainable params: 4,675
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(x_data, y_data, epochs=50, validation_split=0.3) # 학습

Epoch 1/50
4/4 [==============================] - 1s 57ms/step - loss: 0.4285 - acc: 0.4381 - val_loss: 2.7938 - val_acc: 0.6222
Epoch 2/50
4/4 [==============================] - 0s 10ms/step - loss: 0.4086 - acc: 0.0571 - val_loss: 2.7780 - val_acc: 0.8222
Epoch 3/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3984 - acc: 0.3238 - val_loss: 2.7897 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 9ms/step - loss: 0.4018 - acc: 0.4762 - val_loss: 2.7882 - val_acc: 0.0000e+00
Epoch 5/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3995 - acc: 0.4762 - val_loss: 2.7795 - val_acc: 0.0444
Epoch 6/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3976 - acc: 0.2476 - val_loss: 2.7796 - val_acc: 1.0000
Epoch 7/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3979 - acc: 0.0762 - val_loss: 2.7787 - val_acc: 0.9778
Epoch 8/50
4/4 [==============================] - 0s 11ms/step - loss: 0.3974 - acc: 0.4000 -

# Evaluation

In [22]:
model.evaluate(x_data, y_data)

5/5 [==============================] - 0s 3ms/step - loss: 1.1111 - acc: 0.2000


[1.111132264137268, 0.20000000298023224]

# Service

In [24]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [26]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.34098116, 0.33408517, 0.3249337 ]], dtype=float32)

In [27]:
import numpy as np
np.argmax(pred)

0