<a href="https://colab.research.google.com/github/yoonputer/test_deeplearning/blob/master/NaverSentimentAnalysis_loadmodel_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Django Service

In [30]:
import tensorflow as tf

In [31]:
loaded_model = tf.keras.models.load_model('./NaverSentimentAnalysis_LSTM.h5')
loaded_model

In [32]:
!python -m pip install konlpy

In [33]:
import konlpy

In [34]:
  # words = list()
  # for tok in temp_x:
  #   if tok not in stopwords:
  #     words.append(tok)

In [35]:
import pickle

In [36]:
stopwords = pickle.load(open('./stopwords.pkl','rb'))
print(stopwords)

['의', '가', '이', '은', '들', '는', '좀', '잘', '걍', '과', '도', '를', '으로', '자', '에', '와', '한', '하다']


In [37]:
# 감독이 예술이네. --> 웹 사용자가 입력
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
new_sentence

['감독', '예술', '이네', '.']

In [38]:
tokenizer = pickle.load(open('./tokenizer.pkl','rb'))
tokenizer

In [39]:
vob_size = len(tokenizer.word_index)
vob_size

1572

In [40]:
encoded = tokenizer.texts_to_sequences([new_sentence])
encoded
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  92, 128,   1]],
      dtype=int32)

In [41]:
# ['감독이 예술이네.'] --> 웹 사용자가 입력
# loaded_model.predict(['감독이 예술이네.'])

In [42]:
# ['감독이 예술이네.']
score = loaded_model.predict(pad_new)
score

array([[0.50148135]], dtype=float32)

In [43]:
if(score > 0.5):
  print('긍정', score * 100)
else :
  print('부정', score * 100)

긍정 [[50.148136]]


In [43]:
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
encoded = tokenizer.texts_to_sequences([new_sentence])
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
score = loaded_model.predict(pad_new)

In [45]:
def sentiment_predict(sentence):
  okt = konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [47]:
words = '이 영화 꽝이네.'
sentiment_predict(words)

array([[0.5025582]], dtype=float32)

In [48]:
words = '영화가 좋으니 마음도 좋네요'
sentiment_predict(words)

array([[0.51168233]], dtype=float32)