<a href="https://colab.research.google.com/github/yoonputer/test_deeplearning/blob/master/Notescale_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 시계열 데이터 공부
# 나비야 노래를 계명으로 만든것
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [2]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [3]:
# 데이터 사전
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [4]:
range(len(note_seq)-4) # [4,8,12,....]

range(0, 50)

In [5]:
code2idx['g8']

11

In [6]:
dataset = list()
for i in range(len(note_seq)-3):
  subset = note_seq[i:i+4]
  items = list()
  #print(subset)
  for item in subset:
    code2idx[item]
    #print(code2idx[item])
    items.append(code2idx[item])
  #print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2]]


In [7]:
import numpy as np
datasets = np.array(dataset)

In [8]:
x_train = datasets[:,0:3]
x_train.shape

(51, 3)

In [9]:
y_train = datasets[:,3]
y_train.shape

(51,)

In [10]:
len(code2idx)

14

In [11]:
x_train = x_train / 14 # len(code2idx)
x_train[3]

array([0.71428571, 0.57142857, 0.07142857])

# make model

In [12]:
import tensorflow as tf

In [13]:
x_train.shape, x_train[2] # --> tensorflow type(tensor) (50,3,1)
# -- > 스칼라

((51, 3), array([0.14285714, 0.71428571, 0.57142857]))

In [14]:
X_train = np.reshape(x_train,(51,3,1)) # tensor
X_train.shape, X_train[2]

((51, 3, 1), array([[0.14285714],
        [0.71428571],
        [0.57142857]]))

In [15]:
np.unique(y_train) # 없어서 그런거지 데이터 사전을 보면 13개임 (음계)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [16]:
model = tf.keras.models.Sequential()

#tf.keras.layers.LSTM(batch_input_shape=(51, 3, 1)) # batch_size, timesteps, input_dim) -- > (rows, cols, 1) 
                                                   
# # model.add() # input layer
# model.add(tf.keras.layers.LSTM(128, batch_input_shape=(50, 3, 1))) # input and hidden layer
# model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.add(tf.keras.Input(shape=(3,1))) #input layer
model.add(tf.keras.layers.LSTM(128)) # hidden layer
model.add(tf.keras.layers.Dense(13, activation='softmax')) # output layer

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy']) # gadget

In [17]:
hist = model.fit(X_train, y_train, epochs=500, batch_size=5) # 50 / 5 = 10

Epoch 1/500
11/11 [==============================] - 2s 4ms/step - loss: 2.5552 - accuracy: 0.1961 
Epoch 2/500
11/11 [==============================] - 0s 4ms/step - loss: 2.4940 - accuracy: 0.3333
Epoch 3/500
11/11 [==============================] - 0s 4ms/step - loss: 2.4263 - accuracy: 0.3333
Epoch 4/500
11/11 [==============================] - 0s 4ms/step - loss: 2.3284 - accuracy: 0.3333
Epoch 5/500
11/11 [==============================] - 0s 4ms/step - loss: 2.1863 - accuracy: 0.3333
Epoch 6/500
11/11 [==============================] - 0s 5ms/step - loss: 2.0608 - accuracy: 0.3333
Epoch 7/500
11/11 [==============================] - 0s 4ms/step - loss: 1.9941 - accuracy: 0.3333
Epoch 8/500
11/11 [==============================] - 0s 4ms/step - loss: 1.9658 - accuracy: 0.3333
Epoch 9/500
11/11 [==============================] - 0s 4ms/step - loss: 1.9630 - accuracy: 0.3333
Epoch 10/500
11/11 [==============================] - 0s 4ms/step - loss: 1.9457 - accuracy: 0.3333
Epoch 11

In [18]:
model.evaluate(X_train,y_train)

2/2 [==============================] - 0s 7ms/step - loss: 1.0648 - accuracy: 0.5490


[1.0647741556167603, 0.5490196347236633]

In [19]:
X_train[4:5]

array([[[0.57142857],
        [0.07142857],
        [0.5       ]]])

In [20]:
model.predict(X_train[4:5])

array([[3.1485524e-07, 4.6310191e-08, 4.2024498e-05, 1.5930954e-03,
        1.4447596e-06, 4.5676492e-07, 1.8821225e-07, 3.2406482e-03,
        5.2247995e-01, 4.7094080e-01, 1.5960082e-03, 1.0486221e-04,
        1.9792591e-07]], dtype=float32)

In [21]:
first = 0.61538462
second = 0.07692308
third = 0.53846154

In [22]:
#[[[[0.61538462],[0.07692308], [0.53846154]]]]
#pred = model.predict([[[first],[second],[third]]])
pred = model.predict(X_train[0:1])

In [23]:
np.argmax(pred)

10

In [24]:
# code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
#             'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [25]:
# note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
#        'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
#        'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
#        'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']