<a href="https://colab.research.google.com/github/yoonputer/test_deeplearning/blob/master/wine_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

In [2]:
wine = datasets.load_wine()
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [3]:
x_data = wine['data']
x_data.shape

(178, 13)

In [4]:
y_data = wine['target']
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [5]:
import pandas as pd

In [6]:
df_wine = pd.DataFrame(wine.data)
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       178 non-null    float64
 1   1       178 non-null    float64
 2   2       178 non-null    float64
 3   3       178 non-null    float64
 4   4       178 non-null    float64
 5   5       178 non-null    float64
 6   6       178 non-null    float64
 7   7       178 non-null    float64
 8   8       178 non-null    float64
 9   9       178 non-null    float64
 10  10      178 non-null    float64
 11  11      178 non-null    float64
 12  12      178 non-null    float64
dtypes: float64(13)
memory usage: 18.2 KB


In [7]:
df_twine = pd.DataFrame(wine.target)
df_twine

0
0    0
1    0
2    0
3    0
4    0
..  ..
173  2
174  2
175  2
176  2
177  2

[178 rows x 1 columns]

In [8]:
df_wine['y_col'] = df_twine

In [9]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_wine.to_sql('datax_resource', connect, if_exists='append', index=False)
df_twine.to_sql('datay_resource', connect, if_exists='append', index=False)

In [10]:
db_wine = pd.read_sql_query('select * from datax_resource',connect)
db_wine.head(4)

0     1     2     3      4     5  ...     8     9    10    11      12  y_col
0  14.23  1.71  2.43  15.6  127.0  2.80  ...  2.29  5.64  1.04  3.92  1065.0      0
1  13.20  1.78  2.14  11.2  100.0  2.65  ...  1.28  4.38  1.05  3.40  1050.0      0
2  13.16  2.36  2.67  18.6  101.0  2.80  ...  2.81  5.68  1.03  3.17  1185.0      0
3  14.37  1.95  2.50  16.8  113.0  3.85  ...  2.18  7.80  0.86  3.45  1480.0      0

[4 rows x 14 columns]

In [11]:
# x_data = wine['data']
# x_data.shape

dfnpx = df_wine.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12]].to_numpy()
#dfnpx = df_wine.drop('y_col',axis=1).to_numpy()
dfnpx.shape

(178, 13)

In [12]:
dfnpy = df_wine.loc[:,'y_col']
dfnpy

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: y_col, Length: 178, dtype: int64

In [13]:
import numpy as np

In [14]:
# y_data
# y_data, np.unique(y_data)
dfnpy, np.unique(dfnpy)

(0      0
 1      0
 2      0
 3      0
 4      0
       ..
 173    2
 174    2
 175    2
 176    2
 177    2
 Name: y_col, Length: 178, dtype: int64, array([0, 1, 2]))

In [15]:
import tensorflow as tf

In [16]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(13,))) # input layer 

model.add(tf.keras.layers.Dense(64, activation='relu')) # hidden layer
model.add(tf.keras.layers.Dense(64, activation='relu')) # hidden layer

model.add(tf.keras.layers.Dense(3, activation='softmax')) # output layer

model.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy',metrics=['acc'])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                896       
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 195       
Total params: 5,251
Trainable params: 5,251
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.fit(dfnpx, dfnpy, epochs=50, validation_split=0.3)

Epoch 1/50
4/4 [==============================] - 1s 63ms/step - loss: 223.9878 - acc: 0.4194 - val_loss: 0.4822 - val_acc: 0.8889
Epoch 2/50
4/4 [==============================] - 0s 8ms/step - loss: 158.6598 - acc: 0.1855 - val_loss: 9.2015 - val_acc: 0.1111
Epoch 3/50
4/4 [==============================] - 0s 11ms/step - loss: 96.0259 - acc: 0.5242 - val_loss: 2.1362 - val_acc: 0.1111
Epoch 4/50
4/4 [==============================] - 0s 8ms/step - loss: 35.0275 - acc: 0.1774 - val_loss: 6.4503 - val_acc: 0.0000e+00
Epoch 5/50
4/4 [==============================] - 0s 9ms/step - loss: 10.4022 - acc: 0.4355 - val_loss: 57.2656 - val_acc: 0.0000e+00
Epoch 6/50
4/4 [==============================] - 0s 8ms/step - loss: 17.6420 - acc: 0.4758 - val_loss: 79.3170 - val_acc: 0.0000e+00
Epoch 7/50
4/4 [==============================] - 0s 50ms/step - loss: 11.2841 - acc: 0.4758 - val_loss: 82.4853 - val_acc: 0.0000e+00
Epoch 8/50
4/4 [==============================] - 0s 9ms/step - loss: 6.3

# Evaluation

In [19]:
model.evaluate(dfnpx, dfnpy)

6/6 [==============================] - 0s 2ms/step - loss: 34.3256 - acc: 0.6348


[34.325618743896484, 0.6348314881324768]

# Service

In [20]:
dfnpx[25], dfnpy[25]

(array([1.305e+01, 2.050e+00, 3.220e+00, 2.500e+01, 1.240e+02, 2.630e+00,
        2.680e+00, 4.700e-01, 1.920e+00, 3.580e+00, 1.130e+00, 3.200e+00,
        8.300e+02]), 0)

In [21]:
pred = model.predict([[1.305e+01, 2.050e+00, 3.220e+00, 2.500e+01, 1.240e+02, 2.630e+00,
        2.680e+00, 4.700e-01, 1.920e+00, 3.580e+00, 1.130e+00, 3.200e+00,
        8.300e+02]])
pred

array([[0.55189264, 0.4481074 , 0.        ]], dtype=float32)

In [22]:
np.argmax(pred)

0